
"use client"

import { useState, useEffect, useRef } from 'react';
import { UserProfile, WorkoutPlan, ChatMessage, BMICategory } from '@/lib/types';
import { generateSpecializedWorkoutPlan } from '@/ai/flows/generate-specialized-workout-plan';
import { chatWithTrainer } from '@/ai/flows/chat-with-trainer';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { WorkoutCard } from '@/components/WorkoutCard';
import { Progress } from '@/components/ui/progress';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Checkbox } from '@/components/ui/checkbox';
import { 
  Plus, 
  Loader2, 
  LogOut, 
  LayoutDashboard, 
  UserCircle, 
  Settings, 
  MessageSquare, 
  Send,
  Dumbbell,
  Target,
  ShieldAlert,
  Trash2,
  Sparkles,
  ArrowRight,
  Download
} from 'lucide-react';
import { toast } from '@/hooks/use-toast';
import { useVigourStore } from '@/hooks/use-vigour-store';

export function UserDashboard({ 
  user, 
  plans, 
  onLogout 
}: { 
  user: UserProfile; 
  plans: WorkoutPlan[]; 
  onLogout: () => void;
}) {
  const { updateUser, logout, savePlan, markWorkoutComplete } = useVigourStore();
  const [generating, setGenerating] = useState(false);
  const [activeTab, setActiveTab] = useState<'plan' | 'chat' | 'profile' | 'settings'>('plan');
  const [specialRequest, setSpecialRequest] = useState(user.specialPreferences || "");
  const hasAutoGenerated = useRef(false);
  
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [chatInput, setChatInput] = useState("");
  const [sendingChat, setSendingChat] = useState(false);

  // Auto-generate first plan if none exists
  useEffect(() => {
    if (plans.length === 0 && !generating && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      createPlan("Erster personalisierter Ganzkörper-Trainingsplan");
    }
  }, [plans.length, generating]);

  const createPlan = async (requestOverride?: string) => {
    setGenerating(true);
    const finalRequest = requestOverride || specialRequest || "Allgemeine Fitness";
    
    try {
      const result = await generateSpecializedWorkoutPlan({
        fitnessGoal: user.fitnessGoal,
        bmiLevel: user.bmiLevel,
        availableEquipment: user.availableEquipment,
        specializationRequest: finalRequest
      });

      const newPlan: WorkoutPlan = {
        id: Math.random().toString(36).substr(2, 9),
        title: result.planTitle,
        description: result.planDescription,
        dailyWorkouts: result.dailyWorkouts.map(dw => ({
          dayName: dw.dayName,
          focus: dw.focus,
          exercises: dw.exercises.map(ex => ({
            name: ex.name,
            sets: ex.sets,
            repsOrDuration: ex.repsOrDuration,
            trainingMethod: ex.trainingMethod,
            instructions: ex.instructions
          }))
        })),
        userId: 'current-user',
        createdAt: Date.now()
      };

      await savePlan(newPlan);
      toast({ title: "Plan erstellt!", description: "Dein neuer KI-Plan ist bereit." });
    } catch (error) {
      toast({ variant: "destructive", title: "Fehler", description: "Plan konnte nicht generiert werden." });
    } finally {
      setGenerating(false);
    }
  };

  const downloadPlan = () => {
    const activePlan = plans[0];
    if (!activePlan) return;
    
    let text = `VigourAI - Trainingsplan: ${activePlan.title}\n`;
    text += `==================================\n\n`;
    activePlan.dailyWorkouts.forEach(dw => {
      text += `${dw.dayName} - Fokus: ${dw.focus}\n`;
      dw.exercises.forEach(ex => {
        text += `- ${ex.name}: ${ex.sets} Sets, ${ex.repsOrDuration} (${ex.trainingMethod})\n`;
      });
      text += `\n`;
    });
    
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `VigourAI_Plan.txt`;
    a.click();
    toast({ title: "Download gestartet" });
  };

  const handleSendChat = async () => {
    if (!chatInput.trim() || sendingChat) return;
    const userMsg: ChatMessage = { role: 'user', content: chatInput };
    setChatMessages(prev => [...prev, userMsg]);
    setChatInput("");
    setSendingChat(true);

    try {
      const result = await chatWithTrainer({
        message: chatInput,
        userProfile: { fitnessGoal: user.fitnessGoal, bmiLevel: user.bmiLevel }
      });
      setChatMessages(prev => [...prev, { role: 'ai', content: result.response }]);
    } catch (error) {
      toast({ variant: "destructive", title: "Fehler", description: "KI Trainer nicht erreichbar." });
    } finally {
      setSendingChat(false);
    }
  };

  const equipmentOptions = ["Dumbbells", "Resistance Bands", "Pull-up Bar", "Gym Access", "Bench", "Kettlebells", "None"];
  const activePlan = plans[0];
  const completedCount = activePlan?.dailyWorkouts.filter(w => w.isCompleted).length || 0;
  const progress = activePlan ? (completedCount / activePlan.dailyWorkouts.length) * 100 : 0;

  return (
    <div className="min-h-screen bg-background pb-24">
      <header className="sticky top-0 z-30 w-full bg-white/80 backdrop-blur-md border-b">
        <div className="container mx-auto px-4 h-16 flex items-center justify-between">
          <div className="font-headline font-bold text-xl text-primary">VigourAI</div>
          <Button variant="ghost" size="icon" onClick={onLogout}><LogOut className="w-5 h-5" /></Button>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8 max-w-5xl">
        {activeTab === 'plan' && (
          <div className="space-y-10">
            <section className="bg-primary/5 rounded-3xl p-8 border border-primary/10 flex flex-col md:flex-row gap-8 items-center justify-between">
              <div className="space-y-4 max-w-lg w-full">
                <div className="flex items-center gap-2 text-primary font-bold"><Sparkles className="w-5 h-5" /> KI-Trainer aktiv</div>
                <h2 className="text-3xl font-headline font-bold">Dein Plan für heute</h2>
                <div className="flex gap-2">
                  <Input 
                    placeholder="Spezialisierungswunsch..." 
                    value={specialRequest}
                    onChange={(e) => setSpecialRequest(e.target.value)}
                    className="bg-white rounded-full h-12"
                  />
                  <Button onClick={() => createPlan()} disabled={generating} className="rounded-full h-12 w-12 bg-primary">
                    {generating ? <Loader2 className="w-5 h-5 animate-spin" /> : <ArrowRight className="w-5 h-5" />}
                  </Button>
                </div>
              </div>
              {activePlan && (
                <div className="w-full md:w-64 space-y-4 bg-white p-6 rounded-2xl shadow-sm border">
                  <div className="flex justify-between items-center text-sm font-bold">
                    <span>Fortschritt</span>
                    <span className="text-primary">{Math.round(progress)}%</span>
                  </div>
                  <Progress value={progress} className="h-2" />
                  <Button variant="outline" size="sm" onClick={downloadPlan} className="w-full gap-2"><Download className="w-4 h-4" /> Exportieren</Button>
                </div>
              )}
            </section>

            {activePlan && (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {activePlan.dailyWorkouts.map((workout, idx) => (
                  <WorkoutCard key={idx} index={idx} workout={workout} onComplete={() => markWorkoutComplete(activePlan.id, idx)} />
                ))}
              </div>
            )}
            {!activePlan && generating && (
              <div className="flex flex-col items-center justify-center py-20 space-y-4">
                <Loader2 className="w-10 h-10 text-primary animate-spin" />
                <p className="text-muted-foreground animate-pulse">KI erstellt deinen individuellen Plan...</p>
              </div>
            )}
          </div>
        )}

        {activeTab === 'chat' && (
          <div className="max-w-2xl mx-auto h-[600px] flex flex-col bg-white border rounded-2xl overflow-hidden shadow-sm">
            <ScrollArea className="flex-1 p-6">
              <div className="space-y-4">
                {chatMessages.length === 0 && (
                  <div className="text-center py-12 text-muted-foreground">
                    <MessageSquare className="w-10 h-10 mx-auto mb-4 opacity-20" />
                    <p>Frag deinen KI-Trainer nach Tipps oder Erklärungen zu Übungen!</p>
                  </div>
                )}
                {chatMessages.map((msg, i) => (
                  <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                    <div className={`max-w-[80%] p-4 rounded-2xl text-sm ${msg.role === 'user' ? 'bg-primary text-primary-foreground' : 'bg-muted'}`}>
                      {msg.content}
                    </div>
                  </div>
                ))}
                {sendingChat && (
                  <div className="flex justify-start">
                    <div className="bg-muted p-4 rounded-2xl">
                      <Loader2 className="w-4 h-4 animate-spin" />
                    </div>
                  </div>
                )}
              </div>
            </ScrollArea>
            <div className="p-4 border-t flex gap-2">
              <Input 
                placeholder="Frag mich was..." 
                value={chatInput} 
                onChange={e => setChatInput(e.target.value)} 
                onKeyDown={e => e.key === 'Enter' && handleSendChat()} 
              />
              <Button onClick={handleSendChat} disabled={sendingChat || !chatInput.trim()}><Send className="w-4 h-4" /></Button>
            </div>
          </div>
        )}

        {activeTab === 'profile' && (
          <div className="max-w-2xl mx-auto space-y-6">
            <Card>
              <CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Target className="w-5 h-5 text-primary" /> Dein Fokus</CardTitle></CardHeader>
              <CardContent className="space-y-6">
                <div className="space-y-2">
                  <Label>Fitness-Ziel</Label>
                  <Input value={user.fitnessGoal} onChange={e => updateUser({ fitnessGoal: e.target.value })} />
                </div>
                <div className="space-y-3">
                  <Label>BMI-Status</Label>
                  <RadioGroup value={user.bmiLevel} onValueChange={v => updateUser({ bmiLevel: v as BMICategory })} className="grid grid-cols-2 gap-4">
                    {['underweight', 'normal', 'overweight', 'obese'].map(l => (
                      <div key={l} className="flex items-center space-x-2 border p-3 rounded-lg hover:bg-muted/50 cursor-pointer transition-colors">
                        <RadioGroupItem value={l} id={l} />
                        <Label htmlFor={l} className="capitalize cursor-pointer">{l === 'underweight' ? 'Untergewicht' : l === 'normal' ? 'Normal' : l === 'overweight' ? 'Übergewicht' : 'Adipositas'}</Label>
                      </div>
                    ))}
                  </RadioGroup>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Dumbbell className="w-5 h-5 text-primary" /> Dein Equipment</CardTitle></CardHeader>
              <CardContent className="grid grid-cols-2 gap-4">
                {equipmentOptions.map(eq => (
                  <div key={eq} className="flex items-center space-x-2 border p-3 rounded-lg hover:bg-muted/50 cursor-pointer transition-colors">
                    <Checkbox 
                      id={eq} 
                      checked={user.availableEquipment.includes(eq)} 
                      onCheckedChange={checked => {
                        const updated = checked ? [...user.availableEquipment, eq] : user.availableEquipment.filter(i => i !== eq);
                        updateUser({ availableEquipment: updated });
                      }}
                    />
                    <Label htmlFor={eq} className="cursor-pointer">{eq}</Label>
                  </div>
                ))}
              </CardContent>
            </Card>
          </div>
        )}

        {activeTab === 'settings' && (
          <div className="max-w-2xl mx-auto space-y-4">
            <Card>
              <CardContent className="p-0 divide-y">
                <div className="p-4 flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <UserCircle className="w-5 h-5 text-muted-foreground" />
                    <div>
                      <p className="font-bold">{user.name}</p>
                      <Badge variant="outline" className="capitalize text-[10px]">{user.role}</Badge>
                    </div>
                  </div>
                </div>
                <button onClick={onLogout} className="w-full p-4 flex items-center justify-between hover:bg-muted/50 transition-colors">
                  <div className="flex items-center gap-3"><LogOut className="w-5 h-5" /> <span>Abmelden</span></div>
                </button>
                <button onClick={() => logout()} className="w-full p-4 flex items-center justify-between text-destructive hover:bg-destructive/5 transition-colors">
                  <div className="flex items-center gap-3"><Trash2 className="w-5 h-5" /> <span>Daten zurücksetzen</span></div>
                </button>
              </CardContent>
            </Card>
            <div className="p-4 bg-muted/30 border border-dashed rounded-xl flex items-start gap-3">
              <ShieldAlert className="w-5 h-5 text-muted-foreground mt-0.5" />
              <p className="text-xs text-muted-foreground">Deine Daten werden sicher in der Cloud gespeichert. Deine personalisierten Pläne sind nur für dich sichtbar.</p>
            </div>
          </div>
        )}
      </main>

      <nav className="fixed bottom-0 left-0 right-0 h-16 bg-white border-t flex items-center justify-around px-4 z-40 shadow-[0_-2px_10px_rgba(0,0,0,0.05)]">
        <button className={`flex flex-col items-center transition-colors ${activeTab === 'plan' ? 'text-primary' : 'text-muted-foreground'}`} onClick={() => setActiveTab('plan')}>
          <LayoutDashboard className="w-6 h-6" /><span className="text-[10px] font-bold mt-1">Plan</span>
        </button>
        <button className={`flex flex-col items-center transition-colors ${activeTab === 'chat' ? 'text-primary' : 'text-muted-foreground'}`} onClick={() => setActiveTab('chat')}>
          <MessageSquare className="w-6 h-6" /><span className="text-[10px] font-bold mt-1">Trainer</span>
        </button>
        <button className={`flex flex-col items-center transition-colors ${activeTab === 'profile' ? 'text-primary' : 'text-muted-foreground'}`} onClick={() => setActiveTab('profile')}>
          <UserCircle className="w-6 h-6" /><span className="text-[10px] font-bold mt-1">Profil</span>
        </button>
        <button className={`flex flex-col items-center transition-colors ${activeTab === 'settings' ? 'text-primary' : 'text-muted-foreground'}`} onClick={() => setActiveTab('settings')}>
          <Settings className="w-6 h-6" /><span className="text-[10px] font-bold mt-1">Settings</span>
        </button>
      </nav>
    </div>
  );
}
