
"use client"

import { useState, useEffect, useRef } from 'react';
import { WorkoutPlan, ChatMessage, BMICategory } from '@/lib/types';
import { generateSpecializedWorkoutPlan } from '@/ai/flows/generate-specialized-workout-plan';
import { chatWithTrainer } from '@/ai/flows/chat-with-trainer';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { WorkoutCard } from '@/components/WorkoutCard';
import { Progress } from '@/components/ui/progress';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Checkbox } from '@/components/ui/checkbox';
import { 
  Plus, 
  Loader2, 
  LogOut, 
  LayoutDashboard, 
  UserCircle, 
  Settings, 
  MessageSquare, 
  Send,
  Dumbbell,
  Target,
  ShieldAlert,
  Trash2,
  Sparkles,
  ArrowRight,
  Download
} from 'lucide-react';
import { toast } from '@/hooks/use-toast';
import { useVigourStore } from '@/hooks/use-vigour-store';

export function UserDashboard({ onLogout }: { onLogout: () => void; }) {
  const { user, plans, updateUser, savePlan, markWorkoutComplete, authUser, logout } = useVigourStore();
  const [generating, setGenerating] = useState(false);
  const [activeTab, setActiveTab] = useState<'plan' | 'chat' | 'profile' | 'settings'>('plan');
  const [specialRequest, setSpecialRequest] = useState(user?.specialPreferences || "");
  const hasAutoGenerated = useRef(false);
  
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [chatInput, setChatInput] = useState("");
  const [sendingChat, setSendingChat] = useState(false);

  // Automatischer Plan, wenn noch keiner da ist
  useEffect(() => {
    if (user && plans.length === 0 && !generating && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      createPlan("Dein erster Ganzkörper-Trainingsplan");
    }
  }, [user, plans.length, generating]);

  if (!user) return null;

  const createPlan = async (requestOverride?: string) => {
    if (generating) return;
    setGenerating(true);
    const finalRequest = requestOverride || specialRequest || "Allgemeine Fitness";
    
    try {
      const result = await generateSpecializedWorkoutPlan({
        fitnessGoal: user.fitnessGoal,
        bmiLevel: user.bmiLevel,
        availableEquipment: user.availableEquipment,
        specializationRequest: finalRequest
      });

      const newPlan: WorkoutPlan = {
        id: Math.random().toString(36).substr(2, 9),
        title: result.planTitle,
        description: result.planDescription,
        dailyWorkouts: result.dailyWorkouts.map(dw => ({
          dayName: dw.dayName,
          focus: dw.focus,
          exercises: dw.exercises.map(ex => ({
            name: ex.name,
            sets: ex.sets,
            repsOrDuration: ex.repsOrDuration,
            trainingMethod: ex.trainingMethod,
            instructions: ex.instructions
          })),
          isCompleted: false
        })),
        userId: authUser?.uid || 'anonymous',
        createdAt: Date.now()
      };

      await savePlan(newPlan);
      toast({ title: "Plan erstellt!", description: "Dein neuer KI-Plan ist bereit." });
    } catch (error) {
      console.error(error);
      toast({ variant: "destructive", title: "Fehler", description: "Plan konnte nicht generiert werden." });
    } finally {
      setGenerating(false);
    }
  };

  const downloadPlanAsHTML = () => {
    const activePlan = plans[0];
    if (!activePlan) return;
    
    const htmlContent = `
      <!DOCTYPE html>
      <html lang="de">
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>VigourAI - ${activePlan.title}</title>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Space+Grotesk:wght@700&display=swap');
          body { font-family: 'Inter', sans-serif; line-height: 1.6; color: #1a2e1a; max-width: 900px; margin: 40px auto; padding: 20px; background-color: #f0f7f0; }
          .header { text-align: center; margin-bottom: 50px; padding: 50px; background: white; border-radius: 32px; box-shadow: 0 10px 30px rgba(0,0,0,0.05); }
          h1 { font-family: 'Space Grotesk', sans-serif; color: #22c55e; margin: 0; font-size: 3rem; letter-spacing: -1px; }
          .plan-title { font-size: 1.5rem; color: #166534; margin-top: 10px; font-weight: 600; }
          .plan-desc { color: #64748b; margin-top: 15px; font-style: italic; }
          .day { background: white; border-radius: 24px; padding: 35px; margin-bottom: 35px; box-shadow: 0 4px 20px rgba(0,0,0,0.03); }
          .day-title { font-family: 'Space Grotesk', sans-serif; font-weight: bold; font-size: 1.8rem; color: #166534; margin-bottom: 5px; }
          .focus { color: #22c55e; font-weight: bold; text-transform: uppercase; font-size: 0.9rem; margin-bottom: 25px; display: inline-block; background: #f0fdf4; padding: 4px 12px; rounded: 8px; }
          .exercise-list { display: grid; gap: 20px; }
          .exercise { border-left: 5px solid #22c55e; padding: 15px 25px; background: #fafafa; border-radius: 0 16px 16px 0; }
          .ex-name { font-weight: 700; font-size: 1.2rem; color: #1e293b; }
          .ex-meta { font-size: 0.9rem; color: #22c55e; font-weight: 600; margin-top: 5px; }
          .instructions { font-size: 0.95rem; color: #475569; margin-top: 12px; line-height: 1.5; }
          footer { margin-top: 80px; text-align: center; color: #94a3b8; font-size: 0.8rem; }
          @media print { body { background: white; margin: 0; } .header, .day { box-shadow: none; border: 1px solid #eee; } }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>VigourAI</h1>
          <div class="plan-title">${activePlan.title}</div>
          <p class="plan-desc">${activePlan.description}</p>
        </div>
        ${activePlan.dailyWorkouts.map(dw => `
          <div class="day">
            <div class="day-title">${dw.dayName}</div>
            <div class="focus">${dw.focus}</div>
            <div class="exercise-list">
              ${dw.exercises.map(ex => `
                <div class="exercise">
                  <div class="ex-name">${ex.name}</div>
                  <div class="ex-meta">${ex.sets} Sätze • ${ex.repsOrDuration} • ${ex.trainingMethod}</div>
                  <div class="instructions">${ex.instructions}</div>
                </div>
              `).join('')}
            </div>
          </div>
        `).join('')}
        <footer>Diese Datei wurde von VigourAI generiert. Dein persönlicher Fitness-Begleiter.</footer>
      </body>
      </html>
    `;
    
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Mein_VigourAI_Trainingsplan.html`;
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "Plan exportiert", description: "Die HTML-Datei wurde heruntergeladen." });
  };

  const handleSendChat = async () => {
    if (!chatInput.trim() || sendingChat) return;
    const userMsg: ChatMessage = { role: 'user', content: chatInput };
    setChatMessages(prev => [...prev, userMsg]);
    setChatInput("");
    setSendingChat(true);

    try {
      const result = await chatWithTrainer({
        message: chatInput,
        userProfile: { fitnessGoal: user.fitnessGoal, bmiLevel: user.bmiLevel }
      });
      setChatMessages(prev => [...prev, { role: 'ai', content: result.response }]);
    } catch (error) {
      toast({ variant: "destructive", title: "Fehler", description: "KI Trainer nicht erreichbar." });
    } finally {
      setSendingChat(false);
    }
  };

  const activePlan = plans[0];
  const completedCount = activePlan?.dailyWorkouts.filter(w => w.isCompleted).length || 0;
  const progress = activePlan ? (completedCount / activePlan.dailyWorkouts.length) * 100 : 0;

  return (
    <div className="min-h-screen bg-background pb-24">
      <header className="sticky top-0 z-30 w-full bg-white/80 backdrop-blur-md border-b">
        <div className="container mx-auto px-4 h-16 flex items-center justify-between">
          <div className="font-headline font-bold text-xl text-primary flex items-center gap-2">
            <Sparkles className="w-5 h-5 fill-current" /> VigourAI
          </div>
          <Button variant="ghost" size="icon" onClick={onLogout}><LogOut className="w-5 h-5" /></Button>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8 max-w-5xl">
        {activeTab === 'plan' && (
          <div className="space-y-10">
            <section className="bg-primary/5 rounded-3xl p-8 border border-primary/10 flex flex-col md:flex-row gap-8 items-center justify-between">
              <div className="space-y-4 max-w-lg w-full">
                <div className="flex items-center gap-2 text-primary font-bold"><Sparkles className="w-5 h-5" /> KI-Trainer aktiv</div>
                <h2 className="text-3xl font-headline font-bold">Lass uns trainieren</h2>
                <p className="text-muted-foreground text-sm">Ändere deinen Wunsch oder lass die KI deinen Fortschritt analysieren.</p>
                <div className="flex gap-2">
                  <Input 
                    placeholder="Was möchtest du heute?" 
                    value={specialRequest}
                    onChange={(e) => setSpecialRequest(e.target.value)}
                    className="bg-white rounded-full h-12 shadow-sm"
                  />
                  <Button onClick={() => createPlan()} disabled={generating} className="rounded-full h-12 w-12 bg-primary shadow-lg hover:scale-105 transition-transform">
                    {generating ? <Loader2 className="w-5 h-5 animate-spin" /> : <ArrowRight className="w-5 h-5" />}
                  </Button>
                </div>
              </div>
              {activePlan && (
                <div className="w-full md:w-64 space-y-4 bg-white p-6 rounded-2xl shadow-sm border">
                  <div className="flex justify-between items-center text-sm font-bold">
                    <span>Erfolg</span>
                    <span className="text-primary">{Math.round(progress)}%</span>
                  </div>
                  <Progress value={progress} className="h-2" />
                  <Button variant="outline" size="sm" onClick={downloadPlanAsHTML} className="w-full gap-2 border-primary/20 text-primary hover:bg-primary/5">
                    <Download className="w-4 h-4" /> Plan für Browser (HTML)
                  </Button>
                </div>
              )}
            </section>

            {activePlan && (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 animate-in fade-in duration-700">
                {activePlan.dailyWorkouts.map((workout, idx) => (
                  <WorkoutCard key={`${activePlan.id}-${idx}`} index={idx} workout={workout} onComplete={() => markWorkoutComplete(activePlan.id, idx)} />
                ))}
              </div>
            )}
            
            {!activePlan && generating && (
              <div className="flex flex-col items-center justify-center py-20 space-y-4">
                <Loader2 className="w-10 h-10 text-primary animate-spin" />
                <p className="text-muted-foreground animate-pulse">KI erstellt dein Training...</p>
              </div>
            )}
          </div>
        )}

        {activeTab === 'chat' && (
          <div className="max-w-2xl mx-auto h-[600px] flex flex-col bg-white border rounded-2xl overflow-hidden shadow-lg">
            <div className="p-4 border-b bg-muted/30 flex items-center gap-2">
              <MessageSquare className="w-5 h-5 text-primary" />
              <span className="font-bold">Chat mit dem Trainer</span>
            </div>
            <ScrollArea className="flex-1 p-6 bg-muted/5">
              <div className="space-y-4">
                {chatMessages.map((msg, i) => (
                  <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                    <div className={`max-w-[80%] p-4 rounded-2xl text-sm shadow-sm ${msg.role === 'user' ? 'bg-primary text-primary-foreground' : 'bg-white border'}`}>
                      {msg.content}
                    </div>
                  </div>
                ))}
                {sendingChat && (
                  <div className="flex justify-start">
                    <div className="bg-white border p-4 rounded-2xl shadow-sm">
                      <Loader2 className="w-4 h-4 animate-spin text-primary" />
                    </div>
                  </div>
                )}
              </div>
            </ScrollArea>
            <div className="p-4 border-t flex gap-2 bg-white">
              <Input 
                placeholder="Frag deinen Trainer..." 
                value={chatInput} 
                onChange={e => setChatInput(e.target.value)} 
                onKeyDown={e => e.key === 'Enter' && handleSendChat()} 
              />
              <Button onClick={handleSendChat} disabled={sendingChat || !chatInput.trim()} className="bg-primary">
                <Send className="w-4 h-4" />
              </Button>
            </div>
          </div>
        )}

        {activeTab === 'profile' && (
          <div className="max-w-2xl mx-auto space-y-6">
            <Card className="shadow-sm border-none bg-white">
              <CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Target className="w-5 h-5 text-primary" /> Ziele & Fortschritt</CardTitle></CardHeader>
              <CardContent className="space-y-6">
                <div className="space-y-2">
                  <Label>Dein Fitness-Ziel</Label>
                  <Input value={user.fitnessGoal} onChange={e => updateUser({ fitnessGoal: e.target.value })} />
                </div>
                <div className="space-y-3">
                  <Label>BMI Einstufung</Label>
                  <RadioGroup value={user.bmiLevel} onValueChange={v => updateUser({ bmiLevel: v as BMICategory })} className="grid grid-cols-2 gap-4">
                    {['underweight', 'normal', 'overweight', 'obese'].map(l => (
                      <div key={l} className="flex items-center space-x-2 border p-3 rounded-lg hover:bg-muted/50 cursor-pointer bg-white">
                        <RadioGroupItem value={l} id={l} />
                        <Label htmlFor={l} className="capitalize cursor-pointer">{l}</Label>
                      </div>
                    ))}
                  </RadioGroup>
                </div>
              </CardContent>
            </Card>
          </div>
        )}

        {activeTab === 'settings' && (
          <div className="max-w-2xl mx-auto space-y-4">
            <Card className="shadow-sm border-none bg-white overflow-hidden">
              <CardContent className="p-0 divide-y">
                <div className="p-6 flex items-center justify-between bg-primary/5">
                  <div className="flex items-center gap-3">
                    <div className="bg-primary/10 p-3 rounded-full"><UserCircle className="w-8 h-8 text-primary" /></div>
                    <div><p className="font-bold text-lg">{user.name}</p></div>
                  </div>
                </div>
                <button onClick={onLogout} className="w-full p-4 flex items-center justify-between hover:bg-muted/50 transition-colors">
                  <div className="flex items-center gap-3"><LogOut className="w-5 h-5" /> <span>Abmelden</span></div>
                  <ArrowRight className="w-4 h-4 text-muted-foreground" />
                </button>
                <button onClick={() => logout()} className="w-full p-4 flex items-center justify-between text-destructive hover:bg-destructive/5 transition-colors">
                  <div className="flex items-center gap-3"><Trash2 className="w-5 h-5" /> <span>Daten löschen</span></div>
                </button>
              </CardContent>
            </Card>
          </div>
        )}
      </main>

      <nav className="fixed bottom-0 left-0 right-0 h-16 bg-white/90 backdrop-blur-lg border-t flex items-center justify-around px-4 z-40 shadow-sm">
        <button className={`flex flex-col items-center gap-1 ${activeTab === 'plan' ? 'text-primary' : 'text-muted-foreground'}`} onClick={() => setActiveTab('plan')}>
          <LayoutDashboard className="w-5 h-5" /><span className="text-[10px] font-bold">Plan</span>
        </button>
        <button className={`flex flex-col items-center gap-1 ${activeTab === 'chat' ? 'text-primary' : 'text-muted-foreground'}`} onClick={() => setActiveTab('chat')}>
          <MessageSquare className="w-5 h-5" /><span className="text-[10px] font-bold">Chat</span>
        </button>
        <button className={`flex flex-col items-center gap-1 ${activeTab === 'profile' ? 'text-primary' : 'text-muted-foreground'}`} onClick={() => setActiveTab('profile')}>
          <UserCircle className="w-5 h-5" /><span className="text-[10px] font-bold">Profil</span>
        </button>
        <button className={`flex flex-col items-center gap-1 ${activeTab === 'settings' ? 'text-primary' : 'text-muted-foreground'}`} onClick={() => setActiveTab('settings')}>
          <Settings className="w-5 h-5" /><span className="text-[10px] font-bold">Optionen</span>
        </button>
      </nav>
    </div>
  );
}
